version: 2

jobs:
  build:
    working_directory: ~/GithubNetwork
    docker:
        - image: circleci/python:3.6.4
    steps:
        - checkout
        - run:
            name: Install Dependencies
            command: pip install -r requirements.txt
        - run:
            name: Run Unit Tests
            command: python -m unittest -v
        - run: 
          name: Test service
          command: python runner.py alexanderjdupree
            
